# Generated by Django 5.0.3 on 2026-03-23 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, editable=False, max_length=14, unique=True)),
                ('from_address', models.TextField()),
                ('to_address', models.TextField()),
                ('sender_name', models.CharField(blank=True, max_length=140)),
                ('receiver_name', models.CharField(blank=True, max_length=140)),
                ('current_location', models.CharField(blank=True, default='Processing Hub', max_length=180)),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('in_transit', 'In Transit'), ('on_hold', 'On Hold'), ('delivered', 'Delivered')], default='pending', max_length=24)),
                ('hold_active', models.BooleanField(default=False)),
                ('hold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('hold_message', models.CharField(blank=True, default='Your order is on hold: some particular charges apply. Pay now and continue moving your order.', max_length=240)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
