# Generated by Django 5.0.3 on 2026-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentorder',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='item_name',
            field=models.CharField(default='General Cargo', max_length=180),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='item_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
