# Generated by Django 5.0.3 on 2026-03-23 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipmentorder_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentorder',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
