# Generated by Django 5.0.3 on 2026-03-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipmentorder_progress_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentorder',
            name='hold_message',
            field=models.CharField(blank=True, default='Your order is currently on hold due to certain applicable charges. Kindly proceed with the payment to resume processing. Please note that this charge is fully refundable.', max_length=240),
        ),
    ]
