# Generated by Django 5.0.3 on 2026-03-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_shipmentorder_hold_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentorder',
            name='client_notice_option',
            field=models.CharField(choices=[('default_notice', 'Option 1 - Processing Charges Notice'), ('order_charges', 'Option 2 - Order Charges Notice')], default='default_notice', max_length=24),
        ),
    ]
