# Generated by Django 5.0.3 on 2026-04-07 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipmentorder_client_notice_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=180)),
                ('device_id', models.CharField(max_length=120)),
                ('tid', models.CharField(max_length=120)),
                ('item', models.CharField(max_length=200)),
                ('recipient_address', models.CharField(max_length=260)),
                ('recipient_name', models.CharField(max_length=160)),
                ('recipient_number', models.CharField(max_length=90)),
                ('schedule_delivery_date', models.DateField()),
                ('pricing_option', models.CharField(default='Standard rate', max_length=120)),
                ('shipping_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
