# Generated by Django 5.0.3 on 2026-04-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipmentreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentreceipt',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='shipmentreceipt',
            name='location',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='shipmentreceipt',
            name='tid',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
