# Generated by Django 5.0.3 on 2026-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_alter_shipmentreceipt_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentorder',
            name='hold_message',
            field=models.TextField(blank=True, default='Your order is currently on hold due to certain applicable charges. Kindly proceed with the payment to resume processing. Please note that this charge is fully refundable.'),
        ),
    ]
